export {
  WRAPPERS,
  WRAPPER_DEFINITIONS,
  installWrapper,
  installWrappers,
  installSpecificWrappers,
  installWrapperWithSudo,
  uninstallWrapper,
  uninstallWrappers,
  verifyWrappers,
  installGuardedShell,
  installAllWrappers,
  installShieldExec,
  deployInterceptor,
  copyNodeBinary,
  copyBrokerBinary,
  copyShieldClient,
  installAgentNvm,
  patchNvmNode,
  execWithProgress,
  type NvmInstallResult,
  installPresetBinaries,
  installBasicCommands,
  BASIC_SYSTEM_COMMANDS,
  type PresetInstallResult,
  getAvailableWrappers,
  getWrapperDefinition,
  generateWrapperContent,
  getDefaultWrapperConfig,
  wrapperUsesSeatbelt,
  wrapperUsesInterceptor,
  addDynamicWrapper,
  removeDynamicWrapper,
  updateWrapper,
  type WrapperResult,
  type WrapperDefinition,
  type WrapperConfig,
} from './wrappers.js';

export {
  generateRouterWrapper,
  buildInstallRouterCommands,
  buildRemoveRouterCommands,
  findOriginalBinary,
  isRouterWrapper,
  scanForRouterWrappers,
  readPathRegistry,
  writePathRegistry,
  addRegistryInstance,
  removeRegistryInstance,
  pathRegistryPath,
  ROUTER_MARKER,
  type PathRegistry,
  type PathRegistryEntry,
  type PathRegistryInstance,
} from './path-override.js';
