/**
 * macOS Sandbox Profile Generator for Python
 */

import type { SandboxProfileConfig } from '../types.js';

export function generateSandboxProfile(config: SandboxProfileConfig): string {
  const additionalReadPaths = (config.additionalReadPaths || [])
    .map((p) => `(allow file-read* (subpath "${p}"))`)
    .join('\n');

  const additionalWritePaths = (config.additionalWritePaths || [])
    .map((p) => `(allow file-write* (subpath "${p}"))`)
    .join('\n');

  return `;;
;; AgenShield Python Sandbox Profile
;; Generated by @agenshield/patcher
;;

(version 1)
(deny default)

;; ========================================
;; System Libraries & Frameworks
;; ========================================
(allow file-read*
  (subpath "/System")
  (subpath "/usr/lib")
  (subpath "/usr/share")
  (subpath "/Library/Frameworks")
  (subpath "/private/var/db")
  (subpath "/private/etc"))

;; ========================================
;; Python Installation
;; ========================================
(allow file-read*
  (subpath "${config.pythonPath}")
  (subpath "/Library/Frameworks/Python.framework")
  (subpath "/usr/local/lib/python")
  (subpath "/opt/homebrew/lib/python")
  (subpath "/usr/local/Cellar/python"))

;; Python needs to read its own files
(allow file-read*
  (regex #".*\\.py$")
  (regex #".*\\.pyc$")
  (regex #".*\\.pyo$")
  (regex #".*\\.so$")
  (regex #".*\\.dylib$"))

;; ========================================
;; Workspace Access (Read/Write)
;; ========================================
(allow file-read* file-write*
  (subpath "${config.workspacePath}"))

;; Temp directories
(allow file-read* file-write*
  (subpath "/tmp")
  (subpath "/private/tmp")
  (subpath "/var/folders"))

;; ========================================
;; Additional Paths
;; ========================================
${additionalReadPaths}
${additionalWritePaths}

;; ========================================
;; Network (RESTRICTED)
;; ========================================

;; Block all network by default
(deny network*)

;; Allow ONLY broker connection
(allow network-outbound
  (remote tcp "${config.brokerHost}:${config.brokerPort}"))

;; Allow localhost loopback for broker
(allow network-outbound
  (remote tcp "localhost:${config.brokerPort}")
  (remote tcp "127.0.0.1:${config.brokerPort}"))

;; ========================================
;; Process & Signal
;; ========================================
(allow process-fork)
(allow process-exec
  (literal "${config.pythonPath}")
  (literal "/usr/bin/env")
  (literal "/bin/sh")
  (subpath "/usr/local/bin"))

(allow signal (target self))
(allow sysctl-read)

;; ========================================
;; Mach IPC (Limited)
;; ========================================
(allow mach-lookup
  (global-name "com.apple.system.opendirectoryd.libinfo")
  (global-name "com.apple.system.notification_center")
  (global-name "com.apple.CoreServices.coreservicesd")
  (global-name "com.apple.SecurityServer"))

;; ========================================
;; User Defaults (Read-only)
;; ========================================
(allow user-preference-read)
`;
}
