/**
 * sitecustomize.py Generator
 */

import type { SitecustomizeConfig } from '../types.js';

export function generateSitecustomize(config: SitecustomizeConfig): string {
  return `# -*- coding: utf-8 -*-
"""
AgenShield Python Network Isolation

This module patches Python's networking to route all traffic through
the AgenShield broker daemon.

Generated by @agenshield/patcher
"""

import os
import sys
import socket
import functools

# Configuration
_AGENSHIELD_ENABLED = ${config.enabled ? 'True' : 'False'}
_AGENSHIELD_BROKER_HOST = '${config.brokerHost}'
_AGENSHIELD_BROKER_PORT = ${config.brokerPort}
_AGENSHIELD_LOG_LEVEL = '${config.logLevel}'

# Override from environment
if os.environ.get('AGENSHIELD_ENABLED') == 'false':
    _AGENSHIELD_ENABLED = False
if os.environ.get('AGENSHIELD_BROKER_HOST'):
    _AGENSHIELD_BROKER_HOST = os.environ['AGENSHIELD_BROKER_HOST']
if os.environ.get('AGENSHIELD_BROKER_PORT'):
    _AGENSHIELD_BROKER_PORT = int(os.environ['AGENSHIELD_BROKER_PORT'])
if os.environ.get('AGENSHIELD_LOG_LEVEL'):
    _AGENSHIELD_LOG_LEVEL = os.environ['AGENSHIELD_LOG_LEVEL']

# Logging
def _agenshield_log(level, message):
    levels = {'debug': 0, 'info': 1, 'warn': 2, 'error': 3}
    if levels.get(level, 0) >= levels.get(_AGENSHIELD_LOG_LEVEL, 1):
        print(f'[AgenShield] {level.upper()}: {message}', file=sys.stderr)

# Mark as patched
_agenshield_patched = True

if _AGENSHIELD_ENABLED:
    _agenshield_log('info', 'Network isolation enabled')

    # ========================================
    # Socket Patching
    # ========================================

    _original_socket_connect = socket.socket.connect
    _original_create_connection = socket.create_connection

    def _agenshield_is_allowed(host, port):
        """Check if connection to host:port is allowed."""
        # Always allow localhost broker
        if host in ('localhost', '127.0.0.1', '::1') and port == _AGENSHIELD_BROKER_PORT:
            return True
        # Block everything else
        return False

    def _agenshield_socket_connect(self, address):
        """Patched socket.connect that blocks non-localhost connections."""
        try:
            host, port = address[:2]
        except (TypeError, ValueError):
            # Unix socket or other format
            return _original_socket_connect(self, address)

        if not _agenshield_is_allowed(host, port):
            _agenshield_log('warn', f'Blocked connection to {host}:{port}')
            raise ConnectionRefusedError(
                f'AgenShield: Direct connections blocked. '
                f'Use broker at {_AGENSHIELD_BROKER_HOST}:{_AGENSHIELD_BROKER_PORT}'
            )

        return _original_socket_connect(self, address)

    def _agenshield_create_connection(address, timeout=socket._GLOBAL_DEFAULT_TIMEOUT,
                                       source_address=None, *, all_errors=False):
        """Patched socket.create_connection."""
        host, port = address

        if not _agenshield_is_allowed(host, port):
            _agenshield_log('warn', f'Blocked create_connection to {host}:{port}')
            raise ConnectionRefusedError(
                f'AgenShield: Direct connections blocked. '
                f'Use broker at {_AGENSHIELD_BROKER_HOST}:{_AGENSHIELD_BROKER_PORT}'
            )

        return _original_create_connection(address, timeout, source_address,
                                            all_errors=all_errors)

    # Apply socket patches
    socket.socket.connect = _agenshield_socket_connect
    socket.create_connection = _agenshield_create_connection

    # ========================================
    # urllib3 Patching (if available)
    # ========================================

    try:
        import urllib3.connection
        import urllib3.util.connection

        _original_urllib3_create_connection = urllib3.util.connection.create_connection

        def _agenshield_urllib3_create_connection(address, timeout=socket._GLOBAL_DEFAULT_TIMEOUT,
                                                   source_address=None, socket_options=None):
            """Patched urllib3 create_connection."""
            host, port = address

            if not _agenshield_is_allowed(host, port):
                _agenshield_log('warn', f'Blocked urllib3 connection to {host}:{port}')
                raise ConnectionRefusedError(
                    f'AgenShield: Direct connections blocked. '
                    f'Use broker at {_AGENSHIELD_BROKER_HOST}:{_AGENSHIELD_BROKER_PORT}'
                )

            return _original_urllib3_create_connection(address, timeout, source_address,
                                                        socket_options)

        urllib3.util.connection.create_connection = _agenshield_urllib3_create_connection
        _agenshield_log('debug', 'Patched urllib3')

    except ImportError:
        _agenshield_log('debug', 'urllib3 not available, skipping patch')

    # ========================================
    # requests Patching (if available)
    # ========================================

    try:
        import requests
        import json

        _original_requests_request = requests.Session.request

        def _agenshield_requests_request(self, method, url, **kwargs):
            """Patched requests.Session.request that routes through broker."""
            from urllib.parse import urlparse

            parsed = urlparse(url)

            # Allow broker connections
            if parsed.netloc == f'{_AGENSHIELD_BROKER_HOST}:{_AGENSHIELD_BROKER_PORT}':
                return _original_requests_request(self, method, url, **kwargs)

            _agenshield_log('info', f'Routing {method} {url} through broker')

            # Route through broker
            broker_url = f'http://{_AGENSHIELD_BROKER_HOST}:{_AGENSHIELD_BROKER_PORT}/rpc'

            # Prepare broker request
            headers = dict(kwargs.get('headers', {}))
            body = kwargs.get('data') or kwargs.get('json')
            if isinstance(body, dict):
                body = json.dumps(body)

            broker_request = {
                'jsonrpc': '2.0',
                'id': '1',
                'method': 'http_request',
                'params': {
                    'url': url,
                    'method': method.upper(),
                    'headers': headers,
                    'body': body,
                }
            }

            # Make broker request
            response = _original_requests_request(
                self, 'POST', broker_url,
                json=broker_request,
                timeout=kwargs.get('timeout', 30)
            )

            # Parse broker response
            broker_response = response.json()

            if 'error' in broker_response:
                raise requests.exceptions.RequestException(
                    f"AgenShield: {broker_response['error']['message']}"
                )

            result = broker_response['result']

            # Create fake response
            fake_response = requests.models.Response()
            fake_response.status_code = result['status']
            fake_response._content = result['body'].encode('utf-8')
            fake_response.headers = requests.structures.CaseInsensitiveDict(result['headers'])
            fake_response.url = url
            fake_response.request = None

            return fake_response

        requests.Session.request = _agenshield_requests_request
        _agenshield_log('debug', 'Patched requests')

    except ImportError:
        _agenshield_log('debug', 'requests not available, skipping patch')

    # ========================================
    # aiohttp Patching (if available)
    # ========================================

    try:
        import aiohttp

        _original_aiohttp_request = aiohttp.ClientSession._request

        async def _agenshield_aiohttp_request(self, method, url, **kwargs):
            """Patched aiohttp request."""
            from urllib.parse import urlparse

            parsed = urlparse(str(url))

            # Allow broker connections
            if parsed.netloc == f'{_AGENSHIELD_BROKER_HOST}:{_AGENSHIELD_BROKER_PORT}':
                return await _original_aiohttp_request(self, method, url, **kwargs)

            _agenshield_log('warn', f'Blocked aiohttp request to {url}')
            raise aiohttp.ClientError(
                f'AgenShield: Direct connections blocked. '
                f'Use broker at {_AGENSHIELD_BROKER_HOST}:{_AGENSHIELD_BROKER_PORT}'
            )

        aiohttp.ClientSession._request = _agenshield_aiohttp_request
        _agenshield_log('debug', 'Patched aiohttp')

    except ImportError:
        _agenshield_log('debug', 'aiohttp not available, skipping patch')

    _agenshield_log('info', 'Network isolation patches applied')

else:
    _agenshield_log('info', 'Network isolation disabled')
`;
}
