/**
 * Python Wrapper Script Generator
 */

import type { WrapperConfig } from '../types.js';

export function generatePythonWrapper(config: WrapperConfig): string {
  const envVars = Object.entries(config.environmentVariables || {})
    .map(([key, value]) => `export ${key}="${value}"`)
    .join('\n');

  if (config.useSandbox && config.sandboxProfilePath) {
    return `#!/bin/bash
# AgenShield Python Wrapper
# Generated by @agenshield/patcher

set -e

# Environment setup
export PYTHONDONTWRITEBYTECODE=1
${envVars}

# Run Python under sandbox-exec
exec /usr/bin/sandbox-exec -f "${config.sandboxProfilePath}" \\
    "${config.pythonPath}" "$@"
`;
  }

  return `#!/bin/bash
# AgenShield Python Wrapper
# Generated by @agenshield/patcher

set -e

# Environment setup
export PYTHONDONTWRITEBYTECODE=1
${envVars}

# Ensure sitecustomize is loaded
export PYTHONPATH="${config.sitecustomizePath}:\${PYTHONPATH:-}"

# Run Python
exec "${config.pythonPath}" "$@"
`;
}
