/**
 * AgenShield Daemon LaunchDaemon Management
 *
 * Creates and manages a macOS LaunchDaemon for the AgenShield daemon process.
 * Follows the pattern established by openclaw-launchdaemon.ts but uses
 * modern launchctl subcommands (kickstart/disable instead of start/stop).
 *
 * Layout:
 *   Plist:    /Library/LaunchDaemons/com.agenshield.daemon.plist
 *   Launcher: ~/.agenshield/bin/agenshield-daemon-launcher.sh
 *   Logs:     ~/.agenshield/logs/daemon.log + daemon.error.log
 */

import * as fs from 'node:fs';
import * as os from 'node:os';
import * as path from 'node:path';
import { execSync } from 'node:child_process';
import {
  DAEMON_LAUNCHD_LABEL,
  DAEMON_LAUNCHD_PLIST,
  logDir,
} from '@agenshield/ipc';

// ─── Constants ───────────────────────────────────────────────────────────────

const AGENSHIELD_HOST_BUNDLE_ID = 'com.frontegg.AgenShield';

// ─── Types ───────────────────────────────────────────────────────────────────

export interface DaemonServiceConfig {
  /** Path to the daemon binary (SEA) or script */
  daemonPath: string;
  /** HTTP port (default: 5200) */
  port?: number;
  /** HTTP host (default: 127.0.0.1) */
  host?: string;
  /** User home directory of the installing user */
  userHome?: string;
}

export interface DaemonServiceStatus {
  installed: boolean;
  running: boolean;
  pid?: number;
  label: string;
}

export interface DaemonServiceResult {
  success: boolean;
  message: string;
  error?: Error;
}

// ─── Plist Generation ────────────────────────────────────────────────────────

function getLauncherPath(userHome: string): string {
  return path.join(userHome, '.agenshield', 'bin', 'agenshield-daemon-launcher.sh');
}

/**
 * Generate the daemon launcher shell script.
 * Resolves the correct daemon binary and starts it with environment variables.
 */
function generateLauncherScript(config: DaemonServiceConfig): string {
  const userHome = config.userHome || os.homedir();
  const port = config.port || 5200;
  const host = config.host || '127.0.0.1';

  return `#!/bin/bash
# AgenShield Daemon Launcher
# Generated by agenshield service install. Do not edit manually.

export HOME="${userHome}"
export AGENSHIELD_USER_HOME="${userHome}"
export AGENSHIELD_PORT="${port}"
export AGENSHIELD_HOST="${host}"
export PATH="${userHome}/.agenshield/bin:${userHome}/.agenshield/libexec:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"

exec "${config.daemonPath}"
`;
}

/**
 * Generate the LaunchDaemon plist for the AgenShield daemon.
 */
export function generateDaemonPlist(config: DaemonServiceConfig): string {
  const userHome = config.userHome || os.homedir();
  const launcherPath = getLauncherPath(userHome);
  const port = config.port || 5200;
  const host = config.host || '127.0.0.1';

  const hostAppExists = fs.existsSync('/Applications/AgenShield.app');
  const associatedBundleBlock = hostAppExists
    ? `
    <key>AssociatedBundleIdentifiers</key>
    <array>
        <string>${AGENSHIELD_HOST_BUNDLE_ID}</string>
    </array>
`
    : '';

  return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>${DAEMON_LAUNCHD_LABEL}</string>
${associatedBundleBlock}
    <key>ProgramArguments</key>
    <array>
        <string>${launcherPath}</string>
    </array>

    <key>EnvironmentVariables</key>
    <dict>
        <key>HOME</key>
        <string>${userHome}</string>
        <key>AGENSHIELD_USER_HOME</key>
        <string>${userHome}</string>
        <key>AGENSHIELD_PORT</key>
        <string>${port}</string>
        <key>AGENSHIELD_HOST</key>
        <string>${host}</string>
    </dict>

    <key>RunAtLoad</key>
    <true/>

    <key>KeepAlive</key>
    <dict>
        <key>SuccessfulExit</key>
        <false/>
    </dict>

    <key>ThrottleInterval</key>
    <integer>10</integer>

    <key>StandardOutPath</key>
    <string>${logDir(userHome)}/daemon.log</string>

    <key>StandardErrorPath</key>
    <string>${logDir(userHome)}/daemon.error.log</string>

    <key>WorkingDirectory</key>
    <string>${userHome}/.agenshield</string>

    <key>SoftResourceLimits</key>
    <dict>
        <key>NumberOfFiles</key>
        <integer>4096</integer>
    </dict>
</dict>
</plist>
`;
}

// ─── Installation ────────────────────────────────────────────────────────────

/**
 * Install the AgenShield daemon as a macOS LaunchDaemon.
 */
export function installDaemonService(config: DaemonServiceConfig): DaemonServiceResult {
  const userHome = config.userHome || os.homedir();

  try {
    // 1. Create log directory (user-writable under ~/.agenshield/logs)
    const logsDir = logDir(userHome);
    fs.mkdirSync(logsDir, { recursive: true, mode: 0o755 });

    // 2. Install launcher script
    const launcherPath = getLauncherPath(userHome);
    const launcherDir = path.dirname(launcherPath);
    fs.mkdirSync(launcherDir, { recursive: true });
    fs.writeFileSync(launcherPath, generateLauncherScript(config), { mode: 0o755 });

    // 3. Remove stale plist if exists
    try {
      execSync(`sudo launchctl bootout system/${DAEMON_LAUNCHD_LABEL} 2>/dev/null`, { stdio: 'pipe' });
    } catch { /* not loaded */ }

    // 4. Write plist
    const plistContent = generateDaemonPlist(config);
    const tmpPlist = path.join(os.tmpdir(), 'com.agenshield.daemon.plist');
    fs.writeFileSync(tmpPlist, plistContent);
    execSync(`sudo cp "${tmpPlist}" "${DAEMON_LAUNCHD_PLIST}"`, { stdio: 'pipe' });
    execSync(`sudo chown root:wheel "${DAEMON_LAUNCHD_PLIST}"`, { stdio: 'pipe' });
    execSync(`sudo chmod 644 "${DAEMON_LAUNCHD_PLIST}"`, { stdio: 'pipe' });
    fs.unlinkSync(tmpPlist);

    // 5. Bootstrap the plist
    execSync(`sudo launchctl bootstrap system "${DAEMON_LAUNCHD_PLIST}"`, { stdio: 'pipe' });

    return {
      success: true,
      message: 'AgenShield daemon LaunchDaemon installed and loaded',
    };
  } catch (error) {
    return {
      success: false,
      message: `Failed to install daemon service: ${(error as Error).message}`,
      error: error as Error,
    };
  }
}

// ─── Lifecycle Management ────────────────────────────────────────────────────

/**
 * Start the daemon via launchctl (enable + kickstart).
 * Does NOT remove the plist — safe for normal start.
 */
export function startDaemonService(): DaemonServiceResult {
  try {
    try {
      execSync(`sudo launchctl enable system/${DAEMON_LAUNCHD_LABEL}`, { stdio: 'pipe' });
    } catch { /* may already be enabled */ }

    execSync(`sudo launchctl kickstart system/${DAEMON_LAUNCHD_LABEL}`, { stdio: 'pipe' });

    return {
      success: true,
      message: 'Daemon started via launchd',
    };
  } catch (error) {
    return {
      success: false,
      message: `Failed to start daemon service: ${(error as Error).message}`,
      error: error as Error,
    };
  }
}

/**
 * Stop the daemon via launchctl (disable + kill SIGTERM).
 * Keeps the plist — daemon can be restarted.
 */
export function stopDaemonService(): DaemonServiceResult {
  try {
    // Disable prevents KeepAlive from respawning
    try {
      execSync(`sudo launchctl disable system/${DAEMON_LAUNCHD_LABEL}`, {
        stdio: 'pipe',
        timeout: 10_000,
      });
    } catch { /* may already be disabled */ }

    // Send SIGTERM for graceful shutdown
    try {
      execSync(`sudo launchctl kill SIGTERM system/${DAEMON_LAUNCHD_LABEL}`, {
        stdio: 'pipe',
        timeout: 10_000,
      });
    } catch { /* may not be running */ }

    return {
      success: true,
      message: 'Daemon stopped via launchd (plist retained)',
    };
  } catch (error) {
    return {
      success: false,
      message: `Failed to stop daemon service: ${(error as Error).message}`,
      error: error as Error,
    };
  }
}

/**
 * Uninstall the daemon service completely.
 * Bootouts the plist, removes files, and removes log rotation config.
 */
export function uninstallDaemonService(userHome?: string): DaemonServiceResult {
  const home = userHome || os.homedir();

  try {
    // 1. Stop and unload
    try {
      execSync(`sudo launchctl bootout system/${DAEMON_LAUNCHD_LABEL} 2>/dev/null`, { stdio: 'pipe' });
    } catch { /* not loaded */ }

    // 2. Remove plist
    try {
      execSync(`sudo rm -f "${DAEMON_LAUNCHD_PLIST}"`, { stdio: 'pipe' });
    } catch { /* best effort */ }

    // 3. Remove launcher script
    const launcherPath = getLauncherPath(home);
    try {
      fs.unlinkSync(launcherPath);
    } catch { /* may not exist */ }

    return {
      success: true,
      message: 'Daemon service uninstalled',
    };
  } catch (error) {
    return {
      success: false,
      message: `Failed to uninstall daemon service: ${(error as Error).message}`,
      error: error as Error,
    };
  }
}

// ─── Status Checking ─────────────────────────────────────────────────────────

/**
 * Get daemon service status.
 */
export function getDaemonServiceStatus(): DaemonServiceStatus {
  const status: DaemonServiceStatus = {
    installed: false,
    running: false,
    label: DAEMON_LAUNCHD_LABEL,
  };

  // Check if plist is installed
  try {
    fs.accessSync(DAEMON_LAUNCHD_PLIST);
    status.installed = true;
  } catch {
    return status;
  }

  // Check if service is running
  try {
    const output = execSync(`sudo launchctl list ${DAEMON_LAUNCHD_LABEL} 2>/dev/null`, {
      encoding: 'utf-8',
      stdio: ['pipe', 'pipe', 'pipe'],
    });

    // Parse PID from launchctl list output
    const pidMatch = output.match(/"?PID"?\s*[=:]\s*(\d+)/);
    if (pidMatch) {
      status.pid = parseInt(pidMatch[1], 10);
      status.running = true;
    }
  } catch {
    // Not loaded or not running
  }

  return status;
}
